REFPLTV-419: rdkbrowser2: fixed gcc 9.2 build issue
libsoup/soup-date.h:63:30: error: 'GTimeVal' is deprecated:
Use 'GDateTime' instead [-Werror=deprecated-declarations]

oe-core provides libsoup 2.68 whereas RDK should maintain v 2.58
as it has gnutls dependency (higher version have GPLv3 license,
not supported on RDK). So the issue from libsoup headers to be
address by suppressing the gcc flags on rdkbrowser2.

Reason for change: suppress gcc flag as the issue is
from libsoup header
Test Procedure: build rdkbrowser2 from yocto 3.1 (dunfell) framework
Risks: None

Signed-off-by: Moorthy Baskar <moorthy.baskaravenkatraman-sambamoorthy@linaro.org>
Change-Id: I080b3c03d205bd8c2bb40138c05ac1b1d97bbbab