error: 'r' will always evaluate to 'true'
In order to be able to make CXXFLAGS changes from recipe,
upstream must not overwrite such variable.

Reason for change: build fails
Test Procedure: Build the image
Risks: none

Change-Id: I792d2a055ff4814ef0a365f6a683f97cb668d202
Signed-off-by: Hctor Orn Martnez <hector.oron@collabora.co.uk>